# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
    - QnABot
    - releases/*
    exclude:
    - releases/old*

stages:
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: 'windows-2019'

    variables:
      solution: '**/EchoBot1.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/EchoBot1*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/EchoBot1*.csproj'

    - #task: DotNetCoreCLI@2
      #displayName: 'Run unit tests - $(buildConfiguration)'
      #inputs:
      #  command: 'test'
      #  arguments: '--no-build --configuration $(buildConfiguration)'
      #  publishTestResults: true
      #  projects: '**/*.Tests.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      condition: succeeded()


